# Generated by Django 4.1 on 2022-10-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_tempat_wisata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempatwisata',
            name='image_url',
            field=models.TextField(default='https://www.bnaibrith.ca/wp-content/uploads/2020/07/placeholder.png'),
        ),
    ]
