# Generated by Django 4.1 on 2022-11-02 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_izin_usaha', '0013_usaha_alasanditolak'),
        ('info_tempat_wisata', '0003_tempatwisata_wisata_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaftarWisata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaWisata', models.CharField(blank=True, max_length=150)),
                ('hargaWisata', models.CharField(blank=True, max_length=150)),
                ('deskripsiWisata', models.CharField(blank=True, max_length=150)),
                ('tempatWisata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_izin_usaha.usaha')),
            ],
        ),
        migrations.DeleteModel(
            name='TempatWisata',
        ),
    ]
