# Generated by Django 4.1 on 2022-11-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kebutuhan_Pokok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
                ('harga', models.IntegerField()),
                ('image', models.URLField()),
            ],
        ),
    ]
