# Generated by Django 4.1 on 2022-11-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=500)),
                ('news_date', models.DateField()),
                ('news_highlight', models.TextField()),
                ('news_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
