# Generated by Django 4.1 on 2022-10-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisolo', '0002_remove_user_namapemilik'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='namaLengkap',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
