# Generated by Django 4.1 on 2022-10-28 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sisolo', '0004_alter_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pengaduan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal_pengaduan', models.DateField()),
                ('judul_pengaduan', models.CharField(max_length=255)),
                ('deskripsi_pengaduan', models.TextField(null=True)),
                ('status_pengaduan', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisolo.user')),
            ],
        ),
    ]
