# Generated by Django 4.1 on 2022-10-14 16:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendaftaranUsaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaPemilik', models.CharField(max_length=60)),
                ('nomorTeleponPemilik', models.CharField(max_length=13)),
                ('alamatPemilik', models.TextField()),
                ('namaUsaha', models.TextField()),
                ('jenisUsaha', models.TextField()),
                ('alamatUsaha', models.TextField()),
                ('nomorTeleponUsaha', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomorIzinUsaha', models.TextField()),
                ('usaha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_izin_usaha.pendaftaranusaha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ListPendaftaran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusPendaftaran', models.TextField(default='mengajukan')),
                ('usaha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_izin_usaha.pendaftaranusaha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
