# Generated by Django 4.1 on 2022-10-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_izin_usaha', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendaftaranusaha',
            name='nomorTeleponUsaha',
            field=models.CharField(max_length=13),
        ),
    ]
