# Generated by Django 4.1 on 2022-10-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_izin_usaha', '0003_remove_usaha_nomorizinusaha_remove_usaha_usaha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usaha',
            name='alamatPemilik',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usaha',
            name='alamatUsaha',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usaha',
            name='jenisUsaha',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usaha',
            name='namaPemilik',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='usaha',
            name='namaUsaha',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usaha',
            name='nomorIzinUsaha',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='usaha',
            name='nomorTeleponPemilik',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='usaha',
            name='nomorTeleponUsaha',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='usaha',
            name='statusPendaftaran',
            field=models.TextField(blank=True, default='mengajukan'),
        ),
    ]
