# Generated by Django 4.1 on 2022-10-22 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisolo', '0001_initial'),
        ('pendaftaran_izin_usaha', '0005_alter_usaha_statuspendaftaran'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usaha',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisolo.user'),
        ),
    ]
