# Generated by Django 4.1 on 2022-10-22 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pendaftaran_izin_usaha', '0006_alter_usaha_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usaha',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
