# Generated by Django 4.1 on 2022-10-25 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisolo', '0002_remove_user_namapemilik'),
        ('pendaftaran_izin_usaha', '0007_alter_usaha_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usaha',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisolo.user'),
        ),
    ]
