# Generated by Django 4.1 on 2022-10-25 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisolo', '0002_remove_user_namapemilik'),
        ('pendaftaran_izin_usaha', '0008_alter_usaha_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PelakuUsaha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaPemilik', models.CharField(blank=True, max_length=60)),
                ('nomorTeleponPemilik', models.CharField(blank=True, max_length=13)),
                ('alamatPemilik', models.TextField(blank=True)),
                ('fotoKTP', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('fotoWajah', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisolo.user')),
            ],
        ),
    ]
