# Generated by Django 4.1 on 2022-10-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_izin_usaha', '0009_pelakuusaha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelakuusaha',
            name='status',
            field=models.TextField(blank=True, default='Diproses'),
        ),
    ]
