# Generated by Django 4.1 on 2022-10-25 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_izin_usaha', '0010_pelakuusaha_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelakuusaha',
            name='pesan',
            field=models.TextField(blank=True),
        ),
    ]
