# Generated by Django 4.1 on 2022-10-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_izin_usaha', '0012_remove_pelakuusaha_fotoktp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usaha',
            name='alasanDitolak',
            field=models.TextField(blank=True),
        ),
    ]
