# Generated by Django 4.1 on 2022-11-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_sarana_kesehatan', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcenter',
            name='description',
        ),
    ]
