# Generated by Django 4.1 on 2022-10-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_to', models.CharField(max_length=255)),
                ('ref_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('ref_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StopPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_name', models.CharField(max_length=255)),
                ('stop_location', models.URLField(max_length=255)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_transportasi_umum.route')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='transportation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='info_transportasi_umum.transportation'),
        ),
    ]
