# Generated by Django 4.1 on 2022-10-30 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_transportasi_umum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='image',
            field=models.ImageField(upload_to='upload/images/'),
        ),
    ]
