# Generated by Django 4.1 on 2022-10-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_transportasi_umum', '0002_alter_transportation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportation',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
