# Generated by Django 4.1 on 2022-10-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_transportasi_umum', '0003_alter_transportation_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='ref_name',
        ),
        migrations.RemoveField(
            model_name='transportation',
            name='ref_name',
        ),
    ]
