# Generated by Django 4.1 on 2022-11-02 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_transportasi_umum', '0004_remove_route_ref_name_remove_transportation_ref_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='ref_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
