# Generated by Django 4.1 on 2022-11-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempatKuliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kuliner_title', models.CharField(max_length=255)),
                ('kuliner_description', models.TextField(blank=True)),
                ('kuliner_highlight', models.TextField(blank=True)),
                ('kuliner_image', models.ImageField(blank=True, upload_to='')),
                ('image_url', models.TextField(default='https://www.bnaibrith.ca/wp-content/uploads/2020/07/placeholder.png')),
            ],
        ),
    ]
