# Generated by Django 4.1 on 2022-11-01 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pendaftaran_izin_usaha', '0013_usaha_alasanditolak'),
        ('info_kuliner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuKuliner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaMenu', models.CharField(blank=True, max_length=150)),
                ('hargaMenu', models.CharField(blank=True, max_length=50)),
                ('deskripsiMenu', models.CharField(blank=True, max_length=150)),
                ('tempatKuliner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pendaftaran_izin_usaha.usaha')),
            ],
        ),
        migrations.DeleteModel(
            name='TempatKuliner',
        ),
    ]
