# Generated by Django 4.1 on 2022-10-29 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sisolo', '0004_alter_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saran',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('saran_pembangunan', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisolo.user')),
            ],
        ),
    ]
